# Generated by Django 3.2 on 2021-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('client_type', models.CharField(max_length=200)),
                ('industry_type', models.CharField(max_length=200)),
                ('project_manager', models.CharField(max_length=200)),
                ('tax_id', models.CharField(max_length=200)),
                ('bank_accounts', models.CharField(max_length=200)),
            ],
        ),
    ]
