# Generated by Django 3.2 on 2021-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name_1', models.CharField(max_length=200)),
                ('c_num_1', models.CharField(max_length=200)),
                ('c_email_1', models.CharField(max_length=200)),
                ('c_name_2', models.CharField(max_length=200)),
                ('c_num_2', models.CharField(max_length=200)),
                ('c_email_2', models.CharField(max_length=200)),
                ('c_name_3', models.CharField(max_length=200)),
                ('c_num_3', models.CharField(max_length=200)),
                ('c_email_3', models.CharField(max_length=200)),
                ('c_name_4', models.CharField(max_length=200)),
                ('c_num_4', models.CharField(max_length=200)),
                ('c_email_4', models.CharField(max_length=200)),
                ('c_name_5', models.CharField(max_length=200)),
                ('c_num_5', models.CharField(max_length=200)),
                ('c_email_5', models.CharField(max_length=200)),
            ],
        ),
    ]
