# Generated by Django 3.2 on 2021-07-19 19:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210716_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_email_1',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_name_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_num_1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
