# Generated by Django 3.2 on 2021-05-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210514_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientGroup',
        ),
    ]
