# Generated by Django 3.2 on 2021-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210719_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Manager',
        ),
    ]
