# Generated by Django 3.2 on 2021-05-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_clientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.client'),
            preserve_default=False,
        ),
    ]
