# Generated by Django 3.2 on 2021-05-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210521_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='bank',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
