# Generated by Django 3.2 on 2021-05-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210521_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
